logging:
  level:
    org.springframework.boot.devtools: WARN # other values: LOG, ....
---
spring:
  profiles:
    active: local # default profile for H2 DB
---
server:
  port: 443
---
##spring:
##  rabbitmq:
##    host: localhost
##    port: 5672
##    username: guest
##    password: guest
##    virtual-host: /
##  cloud:
##    stream:
##      bindings:
##        fromPortcheckinservice:
##          destination: portcheckinservice-events
##          group: bookingservice
##          consumer:
##            maxAttempts: 3
##        bookingserviceOutput:
##          destination: bookingservice-events
##      rabbit:
##        bindings:
##          fromPortcheckinservice:
##            consumer:
##              acknowledgeMode: AUTO
##              autoBindDlq: true
##              republish-to-dlq: true
##          bookingserviceOutput:
##            producer:
##              transacted: true
#---
spring:
  profiles: production
  jpa:
    database: MYSQL
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
  datasource:
    url: jdbc:mysql://localhost:3306/bookingservice?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
---
spring:
  profiles: local, testing
  jpa:
    database: H2
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
  h2:
    console:
      enabled: true
